# internal metrics port
port: "9644"
# configuration file name
config: config

# Profile for the different fabrics
# Thw one to use is set on the command line
fabrics:
  cisco_sandbox:
    username: admin
    password: ciscopsdt
    apic:
      - https://www.opsdis.com
      - https://sandboxapicdc.cisco.com
      

# Http client settings used to access apic
httpclient:
  insecurehttps: true
  keepalive: 30
  timeout: 30
  tlshandshaketimeout: 10

streams:
  faults:
    class_name: faultInst
    #job_name: aci-faults
    # Additional query parameters for the class query, must start with ? and be separated by &
    root: imdata.0.faultInst.attributes
    query_parameter: ""
    labels:
      - property_name: dn
        regex: "^topology/pod-(?P<podid>[1-9][0-9]*)/node-(?P<nodeid>[1-9][0-9]*)/sys/.*"
    timestamp:
      property_name: lastTransition
    message:
      name: mesg
      format: "%s - %s [dn: %s]"
      # Names are add to the format in the order they are written
      property_names:
        - lastTransition
        - descr
        - dn


  sessions:
    class_name: aaaActiveUserSession
    root: imdata.0.aaaActiveUserSession.attributes
    query_parameter: "?query-target=self&query-target-filter=and(wcard(aaaActiveUserSession.status,\"created\"))"
    message:
      name: mesg
      format: "%s - %s"
      property_names:
        - name
        - status