# internal metrics port
port: 9644
# configuration file name
config: config

# Profile for the different fabrics
# Thw one to use is set on the command line
fabrics:
  cisco_sandbox:
    username: admin
    password: ciscopsdt
    apic:
      - https://www.opsdis.com
      - https://sandboxapicdc.cisco.com
      

# Http client settings used to access apic
httpclient:
  insecurehttps: true
  keepalive: 30
  timeout: 30

streams:
  faults:
    class_name: faultInst
    root: imdata.0.faultInst.attributes
    query_parameter: ""
    labels:
      - property_name: dn
        regex: "^topology/pod-(?P<podid>[1-9][0-9]*)/node-(?P<nodeid>[1-9][0-9]*)/sys/.*"
    message:
      name: message
      format: "%s [dn: %s]"
      # Names are add to the format in the order they are written
      property_names:
        - descr
        - dn


  sessions:
    class_name: aaaActiveUserSession
    query_parameter: "?query-target=self&query-target-filter=and(wcard(aaaActiveUserSession.status,\"created\"))"
    root: imdata.0.aaaActiveUserSession.attributes
    message:
      name: message
      format: "User %s IP %s"
      property_names:
        - name
        - ipAddress