on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, darwin,  windows]
        goarch: [ "arm64", "amd64" ]
        exclude:
          - goarch: arm64
            goos: windows
          - goarch: arm64
            goos: darwin

    steps:
    - uses: actions/checkout@v3
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "1.20"
        binary_name: aci-streamer-${{ env.RELEASE_VERSION }}.${{ matrix.goos }}.${{ matrix.goarch }}
        extra_files: COPYING README.md
